### ISSUE TITLE
请问，这个兼容性很差啊，ie啥的全部打不开，有解决方案吗

### ISSUE THREAD

**Issue by Mr-Yang666** [yezihaohao/react-admin#103]
请问，这个兼容性很差啊，ie啥的全部打不开，有解决方案吗

**Comment by yezihaohao** [comment]
看文档
[https://github.com/yezihaohao/react-admin/issues/12#issuecomment-510295292](https://github.com/yezihaohao/react-admin/issues/12#issuecomment-510295292)
