### ISSUE TITLE
切换到js分支，报错 TypeError: Cannot read property 'isMobile' of undefined

### ISSUE THREAD

**Issue by lonelygoogle** [yezihaohao/react-admin#117]
82 | console.log(auth);
  83 | return (
  84 |     <DocumentTitle title={title}>
> 85 |         <Layout>
     | ^  86 |             {!responsive.data.isMobile && <SiderCustom collapsed={this.state.collapsed} />}
  87 |             <ThemePicker />
  88 |             <Layout style={{ flexDirection: 'column' }}>

**Comment by lonePat** [comment]
请问解决了吗，我也是这样

**Comment by xindanZhao92** [comment]
我也这样

**Comment by yezihaohao** [comment]
一般用yarn 安装依赖都不会出现问题。
由于时间关系，js分支不再维护，请查看最新的master分支的ts版本。
关于redux-alita的用法，请查看https://github.com/yezihaohao/redux-alita。
