### ISSUE TITLE
为啥我跑起来会报错

### ISSUE THREAD

**Issue by StephenWu5** [yezihaohao/react-admin#119]
![image](https://user-images.githubusercontent.com/32475322/90583393-98d30680-e202-11ea-9431-4292ca91e26a.png)

**Comment by StephenWu5** [comment]
我的yarn是最新文档版本的。是通过yarn i 和 yarn start 运行的。

**Comment by StephenWu5** [comment]
大佬不在吗？

**Comment by yezihaohao** [comment]
你拉的是最新的TS版本吗？把node_modules删了，重新用yarn安装包试试

**Comment by StephenWu5** [comment]
我拉取的是master分支的。我试试删除，用yarn安装吧。

**Comment by StephenWu5** [comment]
大佬，还是报错，难道不是master分支吗
![image](https://user-images.githubusercontent.com/32475322/90724981-03af3b00-e2f2-11ea-90ce-975d066b128e.png)

**Comment by yezihaohao** [comment]
没问题就关闭了
