### ISSUE TITLE
项目启动 找不到EchartsArea.tsx  105行option找不到定义

### ISSUE THREAD

**Issue by longtao437** [yezihaohao/react-admin#123]
![image](https://user-images.githubusercontent.com/37266583/93181180-b8f6d680-f76a-11ea-9b53-ccb8240764e9.png)
![image](https://user-images.githubusercontent.com/37266583/93181332-ed6a9280-f76a-11ea-80ad-343d86973eaa.png)
初学者 往指导一下

**Comment by yezihaohao** [comment]
删除node_modules，用yarn重新安装依赖，然后重启

**Comment by ztommyc** [comment]
> ![image](https://user-images.githubusercontent.com/37266583/93181180-b8f6d680-f76a-11ea-9b53-ccb8240764e9.png)
> ![image](https://user-images.githubusercontent.com/37266583/93181332-ed6a9280-f76a-11ea-80ad-343d86973eaa.png)
> 初学者 往指导一下

兄嘚, 问题解决了吗? 我也遇到了, 重新安装依赖重启也不行
node :   v14.15.4
yarn  :   1.22.10
