### ISSUE TITLE
Tuple type '[any, ISetAlita]' of length '2' has no element at index '2'. TS2493 问题

### ISSUE THREAD

**Issue by morgeq** [yezihaohao/react-admin#125]
![QQ截图20200921211111](https://user-images.githubusercontent.com/24974311/93770723-27e29c80-fc4f-11ea-9288-1f1700c6c809.png)
Failed to compile
D:/www/react-admin/src/App.tsx
TypeScript error in D:/www/react-admin/src/App.tsx(96,30):
Tuple type '[any, ISetAlita]' of length '2' has no element at index '2'.  TS2493

    94 | const App = (props: AppProps) => {
    95 |     const [collapsed, setCollapsed] = useState<boolean>(false);
  > 96 |     const [auth, responsive, setAlita] = useAlita(
       |                              ^
    97 |         { auth: { permissions: null } },
    98 |         { responsive: { isMobile: false } },
    99 |         { light: true }
This error occurred during the build time and cannot be dismissed.
!

**Comment by morgeq** [comment]
const [auth, setAlita] = useAlita(
        { auth: { permissions: null } },
        { light: true, }
    );
    const [responsive] = useAlita(
        { responsive: { isMobile: false } },
    );

搞定

**Comment by yezihaohao** [comment]
已修复，拉取最新代码
