### ISSUE TITLE
路由跳转失效

### ISSUE THREAD

**Issue by pxr89** [yezihaohao/react-admin#128]
page页面配置：
`export default () => (
    <Router>
        <Switch>
            {/* <Route component={NotFound}/> */}
            <Route exact path="/app" component={App} />
            <Route exact path="/404" component={NotFound} />
            <Route exact path="/login" component={Login} />
            {/* <Route exact path="/" render={() => <Redirect to="/app/dashboard/index" push />} /> */}
        </Switch>
    </Router>
);
`
chrome 访问
http://localhost:3007/login
匹配不到/login组件，显示空白界面了

**Comment by yezihaohao** [comment]
没复现，可能是你把登录页面的组件删除了。
