### ISSUE TITLE
样式文件在哪里加载的？

### ISSUE THREAD

**Issue by zhuanglong** [yezihaohao/react-admin#13]

**Comment by yezihaohao** [comment]
自定义样式文件有两处引入，根目录的index.js和app.js。antd的样式通过webpack配置按需加载引入（如果不了解antd按需加载可查看其官方文档）。剩下的就是组件里的行内样式。如果有更多的不明白的地方和问题，可以加readme 文档的群进行更多的交流😄

**Comment by zhuanglong** [comment]
@yezihaohao 好的谢谢
