### ISSUE TITLE
报No overload matches this call.错，重新安装依赖没有解决 #137

### ISSUE THREAD

**Issue by 13713668351** [yezihaohao/react-admin#138]
![image](https://user-images.githubusercontent.com/49543295/122023851-844ba480-cdfa-11eb-85c3-c54dc60b7743.png)
![image](https://user-images.githubusercontent.com/49543295/122023885-89a8ef00-cdfa-11eb-831d-b4b47c09be6b.png)

**Comment by 13713668351** [comment]
![image](https://user-images.githubusercontent.com/49543295/122024029-a80eea80-cdfa-11eb-91d0-83208c9b3901.png)

**Comment by limaoscript** [comment]
我用npm安装 启动也报此错误

**Comment by LeeZChuan** [comment]
如果那个echarts图表对你无用，可以删掉那个模块

**Comment by eileen823** [comment]
我也是这个错。。。解决了吗

**Comment by yezihaohao** [comment]
用yarn安装试试
