### ISSUE TITLE
兼容问题

### ISSUE THREAD

**Issue by cgd199158** [yezihaohao/react-admin#20]
请问是否考虑过兼容问题,再测试中发现项目在ie9环境中整体布局出现较大幅度的错位,经审查元素发现使用了flex布局,只兼容ie10+,

**Comment by yezihaohao** [comment]
暂时没有这样的打算。你可以参考下antd官网提供的方案：[https://ant.design/docs/react/getting-started-cn#兼容性](https://ant.design/docs/react/getting-started-cn#兼容性l)
