### ISSUE TITLE
怎样让less只作用当前组件 ？

### ISSUE THREAD

**Issue by zhuanglong** [yezihaohao/react-admin#22]
引入less文件导致样式冲突，怎样让less只作用当前组件 ？

**Comment by coderzzp** [comment]
我目前的做法是：给所在组件的顶层元素增加一个类名

**Comment by yezihaohao** [comment]
推荐使用css-modules。可以尝试下哈
可以参考：[CSS Modules 详解及 React 中实践](https://github.com/camsong/blog/issues/5)
[https://github.com/gajus/react-css-modules](https://github.com/gajus/react-css-modules)

**Comment by 2225025616** [comment]
{
            test: /\.(css|less)$/,
            use: [
              require.resolve('style-loader'),
              {
                loader: require.resolve('css-loader'),
                options: {
                  importLoaders: 1,
                  sourceMap: true,
                  localIndexName:"[name]__[local]___[hash:base64:5]"
                },
              },
              {
                loader: require.resolve('postcss-loader'),
                options: {
                  // Necessary for external CSS imports to work
                  // https://github.com/facebookincubator/create-react-app/issues/2677
                  ident: 'postcss',
                  plugins: () => [
                    require('postcss-flexbugs-fixes'),
                    autoprefixer({
                      browsers: [
                        '>1%',
                        'last 4 versions',
                        'Firefox ESR',
                        'not ie < 9', // React doesn't support IE8 anyway
                      ],
                      flexbox: 'no-2009',
                    }),
                  ],
                },
              },
              {
                loader: require.resolve('less-loader'),
                options: {
                  importLoaders: 1,
                  sourceMap: true,
                  localIndexName:"[name]__[local]___[hash:base64:5]"
                },
              }
