### ISSUE TITLE
使用源码start以后在手机访问，打开菜单，页面会错位

### ISSUE THREAD

**Issue by chinamcafee** [yezihaohao/react-admin#28]
![image](https://user-images.githubusercontent.com/3439961/32934480-7b754e58-cb31-11e7-89f6-996fbd080e33.png)
如图，但是打开演示地址就不会出现这个情况，请问是什么原因?

**Comment by yezihaohao** [comment]
新版antd造成的问题，已处理。建议用yarn下载包和运行程序
