### ISSUE TITLE
请问webpack的代理怎么设置

### ISSUE THREAD

**Issue by SoraYao** [yezihaohao/react-admin#30]
在webpack.config.dev.js中添加了代理的相关设置,但是在测试环境中每次fetch的时候 请求地址还是没有成功代理, 

`devServer:
{
        historyApiFallback: true,
        host: 'localhost',
        port: '3006',
        hot: true,
        inline: true,
        stats: { colors: true },
        proxy: {
            '/api/*': {
                target: 'http://XXXXX',
                pathRewrite: {'^/api' : '/api'},
                changeOrigin: true
            }
        }
    },`

**Comment by yezihaohao** [comment]
可以直接设置package.json.[https://github.com/yezihaohao/react-admin/issues/12](https://github.com/yezihaohao/react-admin/issues/12)
