### ISSUE TITLE
同一个菜单项，比如“首页”，连续点击第二次会报警告

### ISSUE THREAD

**Issue by tryrefine** [yezihaohao/react-admin#32]
Warning: Hash history cannot PUSH the same path; a new entry will not be added to the history stack

**Comment by yezihaohao** [comment]
这个是reactr-router的一个提示，当前路由下的history不能push相同的路径。只有开发环境存在，生产环境不存在，目前还没看到官方有去掉的意思。看不惯的话可以采取一些方法关掉这个提示。具体可以参考[https://github.com/ReactTraining/react-router/issues/4467](https://github.com/ReactTraining/react-router/issues/4467)
