### ISSUE TITLE
项目中redirect方法请教

### ISSUE THREAD

**Issue by mbricks** [yezihaohao/react-admin#35]
项目中
page.js中
<Route exact path="/" render={() => <Redirect to="/app/dashboard/index" push />} />    
index.js中
<Route exact path="/app/dashboard/index" component={Dashboard} />

page页面redirect到index.页面里的首页，是怎么工作的。为什么没掉成功呢

**Comment by yezihaohao** [comment]
使用Redirect组件，当访问根路由/时，返回一个重定向组件，重定向到首页。具体一些细节，你可以查看react-router的文档[https://github.com/ReactTraining/react-router](https://github.com/ReactTraining/react-router)
