### ISSUE TITLE
请作者解惑。

### ISSUE THREAD

**Issue by Helaiqu** [yezihaohao/react-admin#38]
![dk 9 6lho 1 ieart2_gbq](https://user-images.githubusercontent.com/16275345/35478520-904f86e6-041a-11e8-8c80-b53fe77541e5.png)；
图中圈住的部分，请问要表达什么意思？请恕我看来看去也感觉它没什么意义。

**Comment by yezihaohao** [comment]
stateName不传的话默认用函数名作为state里面的key
