### ISSUE TITLE
不能显示图标

### ISSUE THREAD

**Issue by somewhereMrli** [yezihaohao/react-admin#4]

**Comment by yezihaohao** [comment]
麻烦能不能具体点呢？

**Comment by somewhereMrli** [comment]
![qq 20170711090848](https://user-images.githubusercontent.com/16183674/28046824-fb93043c-6618-11e7-8a4c-10c5aa48ddc8.png)
就是预览地址里面啊、
还有你这个不能在window下面编译啊，
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

我启动报 
Error: Cannot find module '../config/webpackDevServer.config'



![Uploading QQ图片20170711091818.png…]()

**Comment by yezihaohao** [comment]
哦。这个问题周末更新的时候少提交了一个文件，昨晚已经补上了。重新拉取下代码再启动就可以了😄
