### ISSUE TITLE
直接输入url地址造成组件重复渲染多次？

### ISSUE THREAD

**Issue by lingjiaju** [yezihaohao/react-admin#44]
运行后直接输入http://localhost:3006/#/app/ui/buttons地址，看到buttons展示的页面，但是发现Buttons里面的render被重复加载多次，如果通过鼠标点菜单进来不会有这个问题，只限于直接输入url的情况，这个是antd本身的问题吗？

**Comment by yezihaohao** [comment]
群里面讨论过了吧
