### ISSUE TITLE
如何做到 手机端对滚动很慢的处理 & Content高度 的两全？

### ISSUE THREAD

**Issue by abduwaly** [yezihaohao/react-admin#46]
App.js
`
// 手机端对滚动很慢的处理 responsive.data.isMobile && ( <style> #root{ height: auto; } </style> )
`

你加的这个之后（我并不知道有没有对手机端滚动快慢有影响），但是在Content里面内容不多的情况下会比较难看（Footer会跑到屏幕中央等），有没有什么建议做到两全？

**Comment by yezihaohao** [comment]
把这个注释掉吧，我测了下，移动端滚动没有问题。antd的content组件会自动填充中间的空白
