### ISSUE TITLE
谷歌浏览器报错？

### ISSUE THREAD

**Issue by davychan1985** [yezihaohao/react-admin#47]
访问http://localhost:3006/#/app/auth/basic 时，页面报错。
![_20180429012530](https://user-images.githubusercontent.com/24986002/39399238-da4ff88a-4b09-11e8-92c4-c198b3c1d613.png)

**Comment by yezihaohao** [comment]
测了下没有报错，看下是否改过代码，打印下auth对象调试

**Comment by davychan1985** [comment]
卸载谷歌浏览器，重装后，就可以了，没有报错了。谢谢@yezihaohao。
