### ISSUE TITLE
npm install 失败

### ISSUE THREAD

**Issue by wjkang** [yezihaohao/react-admin#49]
npm 5.6.0
node 9.0.0
npm ERR! Unexpected end of JSON input while parsing near '..."2.x - 4.x"},"directo'

npm ERR! A complete log of this run can be found in:
npm ERR!     D:\node\node_global_cache\_logs\2018-05-21T07_30_33_055Z-debug.log

能google到的方法都试了

**Comment by yezihaohao** [comment]
配置一下淘宝镜像源，删掉node_modules重新安装试试，不行的话再试试yarn

**Comment by wjkang** [comment]
解决了，要换到npm 4
