### ISSUE TITLE
还没有图标啊，有个文件下载不下来

### ISSUE THREAD

**Issue by somewhereMrli** [yezihaohao/react-admin#5]
![qq 20170711103022](https://user-images.githubusercontent.com/16183674/28048528-23c1f156-6624-11e7-9259-9826efba357b.png)
你本地可以访问到图标？

**Comment by yezihaohao** [comment]
![qq 20170711104611](https://user-images.githubusercontent.com/23539868/28048870-529999dc-6626-11e7-98ef-17ba1fc13ab0.png)
我这里是正常显示的。
你不能访问这个网址？https://at.alicdn.com/t/font_zck90zmlh7hf47vi.woff。这个是antd字体的cdn地址，antd ui需要先从这个地址下载字体，然后字体才能正常显示

**Comment by somewhereMrli** [comment]
对，看来公司把这个墙了，可以换成本地的么？

**Comment by yezihaohao** [comment]
https://github.com/ant-design/antd-init/tree/master/examples/local-iconfont#local-hosted-iconfont
你参照这个试试呢

**Comment by somewhereMrli** [comment]
可以了，谢谢哈
