### ISSUE TITLE
项目开发和生产依赖包位置不合理

### ISSUE THREAD

**Issue by wjf444128852** [yezihaohao/react-admin#50]
package.json内：dependencies下都是生产环境的依赖，devDependencies下都是开发环境的依赖，你这有点凌乱啊，是故意为之还是？

**Comment by richard2018** [comment]
react-admin对devDependencies和dependencies的依赖配置是不正确的。

**Comment by wjf444128852** [comment]
@richard2018 不是太明白。能具體一點嗎？

**Comment by yezihaohao** [comment]
https://github.com/facebook/create-react-app/issues/4310

**Comment by wjf444128852** [comment]
@yezihaohao 了解了~
