### ISSUE TITLE
导入依赖出错。

### ISSUE THREAD

**Issue by MyDinnerIsReady** [yezihaohao/react-admin#54]
你好。我把项目down下来以后，运行npm install 安装相关依赖，但是报错：
npm WARN deprecated babel-preset-es2015@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update! 
npm WARN deprecated browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
npm WARN deprecated istanbul-lib-hook@1.2.1: 1.2.0 should have been a major version bump
npm ERR! Unexpected end of JSON input while parsing near '..."rc-tooltip":"~2.6.4"'

**Comment by MyDinnerIsReady** [comment]
应该和源或者npm版本有关，我换了淘宝源以后换了一个报错了。
npm ERR! Unexpected end of JSON input while parsing near '...name":"rc-tabs","vers'

**Comment by yezihaohao** [comment]
没遇到过这个错误，建议安装最新的稳定版本的npm或者yarn，删除node_modules，重新安装试试。ps:不要用cnpm

**Comment by MyDinnerIsReady** [comment]
最后清了一下npm缓存，换了默认源解决了，都是淘宝源的锅。

2018-07-24 16:05 GMT+08:00 yezihaohao <notifications@github.com>:
