### ISSUE TITLE
编译失败

### ISSUE THREAD

**Issue by tonyjt** [yezihaohao/react-admin#55]
./src/components/index.js
  Line 26:  Unexpected '!' in 'bundle-loader?lazy!./ui/Wysiwyg'. Do not use import syntax to configure webpack loaders  import/no-webpack-loader-syntax

Search for the keywords to learn more about each error.

**Comment by yezihaohao** [comment]
eslint 配置添加"import/no-webpack-loader-syntax": 0
建议用react-loadable组件，后续也会剔除这种用法
