### ISSUE TITLE
配置babel-polyfill来兼容IE9和10，但是各种配置都不成功，大佬能不能做一下IE的兼容啊

### ISSUE THREAD

**Issue by 593684204** [yezihaohao/react-admin#56]
跪求大佬更新一下IE9和IE10的兼容配置

**Comment by yezihaohao** [comment]
安装babel-polyfill，在webpack.config.dev.js和webpack.config.prod.js的entry增加配置
```
entry: [
'babel-polyfill',
paths.appIndexJs,
]
```
你测试下，我这没IE9

**Comment by 593684204** [comment]
我在webpack.config.dev.js和webpack.config.prod.js的entry增加配置entry: [
'babel-polyfill',
paths.appIndexJs,
]测试以后还是不行，然后又在index.js的顶部也import‘babel-polyfill’，同时安装了babel-preset-env，在package.json中添加了"babel": {
    "presets": [
      "env",
      "react-app"
    ]
  }，可还是不行，报错为：
![aaaaa5](https://user-images.githubusercontent.com/30250692/44249750-e1c2df80-a223-11e8-91ec-8b4d458cfcc0.png)

**Comment by yezihaohao** [comment]
试试babel-preset-es2015-ie  [https://github.com/jmcriffey/babel-preset-es2015-ie](https://github.com/jmcriffey/babel-preset-es2015-ie)

参考：[ES6 + Webpack + React + Babel 如何在低版本浏览器上愉快的玩耍（下）](https://segmentfault.com/a/1190000006930013)
