### ISSUE TITLE
调整窗口大小时，有问题

### ISSUE THREAD

**Issue by renshou2003** [yezihaohao/react-admin#57]
当任意调整窗口大小时会导致内容显示页面重新渲染
routes/index.js render()方法中的<Switch>...</Switch>应该在componentWillMount时存入state中比较合适

**Comment by yezihaohao** [comment]
已修复
[https://github.com/yezihaohao/react-admin/commit/967bf36778da40b458689b658112dab8961fac42](https://github.com/yezihaohao/react-admin/commit/967bf36778da40b458689b658112dab8961fac42)
