### ISSUE TITLE
可否分享一下关于登录验证方面的相关思路

### ISSUE THREAD

**Issue by fe719319448** [yezihaohao/react-admin#6]
最近也在做这样一个后台系统，后台里面所有的页面都是需要登录状态才可以访问的，并且对于账号有对应权限，还有保持登录状态方面的思路，求分享

**Comment by yezihaohao** [comment]
单页应用的话我觉得redux是这个不错的选择，全页面共享state，当然包括你说的用户的登录状态和信息。浏览器需要保存登录信息的话可以用cookie或者本地存储等
