### ISSUE TITLE
babel-preset-es2015需要升级了

### ISSUE THREAD

**Issue by mymhj** [yezihaohao/react-admin#60]
npm WARN deprecated browserslist@2.11.3: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
npm WARN deprecated babel-preset-es2015@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs
.io/env to update!

npm install，出项上面的提示。辛苦

**Comment by chailiangyang** [comment]
npm WARN deprecated browserslist@2.11.3: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
npm WARN deprecated babel-preset-es2015@6.24.1: 🙌 Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs
.io/env to update!

npm install，出项上面的提示。辛苦

**Comment by yezihaohao** [comment]
已处理
