### ISSUE TITLE
升级webpack4  打包之后css没有加载出来

### ISSUE THREAD

**Issue by sundjly** [yezihaohao/react-admin#61]
![image](https://user-images.githubusercontent.com/23523003/47403634-c670d500-d77c-11e8-920b-8d699b0131e4.png)

**Comment by yezihaohao** [comment]
是拉取的最新的代码打包的？我打包没问题。（如果是以前的版本单独升级webpack的话，webpack配置可能需要做修改，具体可以参考最新脚手架的配置或者查询webpack官方文档）

**Comment by sundjly** [comment]
最后发现是我测试的问题，我用http-server加载一个本地服务测试是没有问题的，非常感谢你的回答

**Comment by sundjly** [comment]
非常感谢你，发现应该是升级webpack4没有替换的问题，删除重新拉取代码，用http-server在本地测试打包的项目，没有问题了
