### ISSUE TITLE
同一页面绘制多个Echarts，数据全部变为最后一个

### ISSUE THREAD

**Issue by cchang1986** [yezihaohao/react-admin#62]
在同一页面绘制了8个Echarts，但最后出来的效果所有图表都是最后一个图表的数据
相关代码如下：  循环中调用        
  propsObj = {
                data: data, date: date, title: title
            };

            component.push(
                <div className="gutter-box" key={index}>
                    <Card title={title} bordered={false}>
                        <EchartsArea {...propsObj}/>
                    </Card>
                </div>
            );

**Comment by yezihaohao** [comment]
每次循环传入组件的propsObj对象值是一样的？

**Comment by zhoujinzong** [comment]
每次传入的propsObj对象值都不一样，循环中把得到的数据处理了之后再每个propsObj对象中赋值，然后return出去，得到的结果是一个对象数据，再给render进行渲染，第一张图是处理循环结果return的函数部分代码，第二个张图是结果集，第三第四是每一个对象的propsObj，都是不同的，第五张图是echartArea的设置，每次进入echartArea组件的时候得到的值也是不同的，页面也成功渲染出来了，不过最后曲线显示的都是最后一组的数据的，一直想不明白是哪里有设置的错误，请指教

![1540436846](https://user-images.githubusercontent.com/19348710/47473793-b9201d00-d846-11e8-9893-6ae88729fc10.png)
![1540437158](https://user-images.githubusercontent.com/19348710/47473836-eec50600-d846-11e8-862d-93d25fc2e9f2.png)
![1540438178](https://user-images.githubusercontent.com/19348710/47474429-77dd3c80-d849-11e8-8e86-f23974014ec7.png)
![1540438193](https://user-images.githubusercontent.com/19348710/47474435-7b70c380-d849-11e8-880a-63f90bfee6c9.png)
![1540438497](https://user-images.githubusercontent.com/19348710/47474566-18336100-d84a-11e8-84c3-b94d1b445e58.png)

**Comment by zhoujinzong** [comment]
我这边在原框架处理了一下只显示了我代码的曲线部分，希望能够得到问题的解答

[react-admin-master.zip](https://github.com/yezihaohao/react-admin/files/2518714/react-admin-master.zip)

**Comment by yezihaohao** [comment]
@zhoujinzong  你在EchartsArea的render里面打印option看看，最后都是同一个对象，简单的做法就是用函数生成这个option或者把option变量提到class里面生成。
![qq 20181027144253](https://user-images.githubusercontent.com/23539868/47600783-24a9ec00-d9f9-11e8-86ce-cf15a03ee9e5.png)
![qq 20181027150124](https://user-images.githubusercontent.com/23539868/47600787-3c817000-d9f9-11e8-992b-917bf1dd41ea.png)

**Comment by zhoujinzong** [comment]
解决了，非常感谢
