### ISSUE TITLE
关于登录控制的问题

### ISSUE THREAD

**Issue by zhoujinzong** [yezihaohao/react-admin#63]
在使用react-admin的过程中我们对用户登录的权限有一定的控制，不过我看了这部分代码有些地方不是很明白，希望能够得到你的解答。截图中在props设置的auth的data下那些属性是怎么设置的，还有permissions和fetchData函数不是很明白指定的这两个funcName与stateName是如何控制，谢谢
![1541673053](https://user-images.githubusercontent.com/19348710/48193174-d72c6800-e384-11e8-8bc9-6908e80ab882.png)

**Comment by yezihaohao** [comment]
这个主要是用redux存储接口返回的登录权限数据，funcName表示调用定义的接口函数，stateName表示redux中存储key值，参考axios，action以及reducer 三个文件夹

**Comment by zhoujinzong** [comment]
好的，谢谢
