### ISSUE TITLE
如何配置CSS module？

### ISSUE THREAD

**Issue by ZhangMingZhao1** [yezihaohao/react-admin#64]
RT

**Comment by yezihaohao** [comment]
已经支持，具体用法：
[https://github.com/yezihaohao/react-admin/blob/master/CHANGELOG.md#2018-01-12](https://github.com/yezihaohao/react-admin/blob/master/CHANGELOG.md#2018-01-12)

具体配置：
[https://github.com/yezihaohao/react-admin/blob/master/config/webpack.config.prod.js](https://github.com/yezihaohao/react-admin/blob/master/config/webpack.config.prod.js)
[https://github.com/yezihaohao/react-admin/blob/master/config/webpack.config.dev.js](https://github.com/yezihaohao/react-admin/blob/master/config/webpack.config.dev.js)
