### ISSUE TITLE
npm i 出错

### ISSUE THREAD

**Issue by chailiangyang** [yezihaohao/react-admin#66]
npm ERR! Unexpected end of JSON input while parsing near '...nk346MfXXYZjZAO5am6MB'

npm ERR! A complete log of this run can be found in:
npm ERR!     npm-cache\_logs\2018-12-19T06_59_57_058Z-debug.log

这个错是什么问题啊

**Comment by yezihaohao** [comment]
保证npm是最新稳定版，如果没有添加淘宝镜像源就多试试几次，或者用yarn试试
