### ISSUE TITLE
fails to  run build

### ISSUE THREAD

**Issue by bindazhong** [yezihaohao/react-admin#7]
react-admin zhongbingda$ npm run build

> demo@0.1.0 build /Users/zhongbingda/work/web/git/react-admin
> node scripts/build.js

Creating an optimized production build...
Failed to compile.

Module not found: Error: Can't resolve '@/components/BreadcrumbCustom' in '/Users/zhongbingda/work/web/git/react-admin/src/components/auth'

**Comment by yezihaohao** [comment]
生产环境的配置文件别名多加了单引号，已修复，重新拉下代码即可
