### ISSUE TITLE
Warning: Cannot update during an existing state transition (such as within `render`). Render methods should be a pure function of props and state.

### ISSUE THREAD

**Issue by ntuwang** [yezihaohao/react-admin#70]
![image](https://user-images.githubusercontent.com/11935122/55272318-d6757d80-52f5-11e9-923a-94c2fa3ead91.png)
一直会有这个Warning，我把所有的路由及组件 都删掉  只保留 左边和上方导航，依然会有这个告警，但我看到你的demo 却没有告警，请问下 啥原因啊？

**Comment by yezihaohao** [comment]
已修复，啦最新代码试试

**Comment by ntuwang** [comment]
我试了下修改src/routers/index.js 应该就可以了吧，我跟你最新版本差了好几个版本了，改动已经比较大了，没办法merge
