### ISSUE TITLE
用户登录成功了，已经将user数据存入缓存，头部组件里面又获取user数据，判断并调取接口，感觉if判断是多余的？

### ISSUE THREAD

**Issue by wdlhao** [yezihaohao/react-admin#78]
login.jsx组件中，登录成功后，已经将数据存入到缓存；
 componentDidUpdate() { // React 16.3+弃用componentWillReceiveProps
        const { auth: nextAuth = {}, history } = this.props;
        if (nextAuth.data && nextAuth.data.uid) { // 判断是否登陆成功
            localStorage.setItem('user', JSON.stringify(nextAuth.data)); //将登录之后的用户信息保存到localStorage
            history.push('/');//登录成功后，路由定位到首页
        }
    }
 HeaderCustom.jsx组件中，_user永远为true
componentDidMount() {
        const QueryString = queryString();
        const _user = JSON.parse(localStorage.getItem('user')) || '测试';
        if (!_user && QueryString.hasOwnProperty('code')) { // 多余的判断
            gitOauthToken(QueryString.code).then(res => {
                gitOauthInfo(res.access_token).then(info => {
                    this.setState({
                        user: info
                    });
                    localStorage.setItem('user', JSON.stringify(info));
                });
            });
        } else {
            // 得到user信息后，进行重新赋值
            this.setState({
                user: _user
            });
        }
    };

**Comment by yezihaohao** [comment]
GitHub第三方登录使用，如果有不需要的功能可以去掉
