### ISSUE TITLE
npm install 失败

### ISSUE THREAD

**Issue by daichao** [yezihaohao/react-admin#8]
clone博主最新版本的项目到本地后，执行npm i,直接报错，报错信息如下：
npm ERR! Unexpected end of input at 1:72287
npm ERR! ","optimist":"0.2.x","uglify-js":"2.2.x","async":"0.1.x","enhanced-re
npm ERR!                                                                      ^

ps:本人开发环境为：node:8.2.1,npm:5.3.0

**Comment by yezihaohao** [comment]
我拉代码重新装了包，没遇到问题呢。你可以把npm配置淘宝镜像源后再试试呢。
npm config set registry https://registry.npm.taobao.org --global
npm config set disturl https://npm.taobao.org/dist --global
依次运行上面两句命令就可以配置镜像源了
