### ISSUE TITLE
代码耦合太强了，能再组织下就好了

### ISSUE THREAD

**Issue by timer-cp** [yezihaohao/react-admin#80]

**Comment by timer-cp** [comment]
代码组织的太烂了，不得不来吐槽了

**Comment by yezihaohao** [comment]
> 代码组织的太烂了，不得不来吐槽了

具体哪些地方优化呢？请指点或者PR

**Comment by timer-cp** [comment]
建议用react-redux来管理数据，将框架和第三方功能分开；本来想用你这个快速开发个后台，但看了两天感觉要自己掌握太麻烦，也可能是我react掌握的不好的原因吧，不过最后还是重新写了个。

**Comment by yezihaohao** [comment]
> 建议用react-redux来管理数据，将框架和第三方功能分开；本来想用你这个快速开发个后台，但看了两天感觉要自己掌握太麻烦，也可能是我react掌握的不好的原因吧，不过最后还是重新写了个。

redux 项目中有使用的，可以看下功能更新说明或者issue等，当然是否所有的状态都该用redux，因人，项目和场景而异，模板中只把典型的使用场景列出来，如果觉得redux用在所有地方，那自己替换即可。框架和第三方功能分开是指什么？react，echarts等代码拆分打包？如果是这个的话，那这个拆分打包的功能也是因项目和场景而异，webpack只需要加简单的配置就行。。不知还有其他的优化地方吗？还请指点

**Comment by timer-cp** [comment]
指点不敢当，大佬。个人感觉还是数据管理和模块功能划分这块比较麻烦。

**Comment by yezihaohao** [comment]
我也是个还在学习中的菜鸟，如果你有更好的想法的话，欢迎和感谢PR分享😄
