### ISSUE TITLE
多级嵌套路由改路由配置文件不支持

### ISSUE THREAD

**Issue by leishihong** [yezihaohao/react-admin#81]
{
          key: '/app/ui/buttons',
          title: '按钮',
          component: 'Buttons',
          subs: [
            {
              key: '/app/ui/buttons/page',
              title: '按钮123',
              component: 'page',
            },
          ],
        },

**Comment by yezihaohao** [comment]
暂时只支持二级菜单，三级的可以自己加，有时间的话也欢迎PR
