### ISSUE TITLE
axios中tools.js post请求参数错误

### ISSUE THREAD

**Issue by Lingdeqing** [yezihaohao/react-admin#82]
https://github.com/yezihaohao/react-admin/blob/master/src/axios/tools.js
 axios
        .post(url, data, headers)
改成
 axios
        .post(url, data, {headers})

**Comment by yezihaohao** [comment]
把名字修改了下，headers --> config
[https://github.com/yezihaohao/react-admin/commit/ca206a7382106da6c1f04185cea60c58a59e6e5a](https://github.com/yezihaohao/react-admin/commit/ca206a7382106da6c1f04185cea60c58a59e6e5a)
