### ISSUE TITLE
请问左侧菜单的选中状态保持是怎么做到的呢？

### ISSUE THREAD

**Issue by mcuking** [yezihaohao/react-admin#9]
能大概描述下您的这个项目的状态保持大概是下的原理吗？是使用了localStorage还是redux呢？

**Comment by yezihaohao** [comment]
左侧菜单的选中用的是组件的state。初始化或props改变的时候，截取地址栏相应位置的字符，赋值给组件的state并设置antd menu组件的openkey，方法比较简单，不过我觉得这个操作antd具备的话再好不过。至于localStorage和redux在新增的权限模块用到。所有具体的操作还是建议你拉取代码运行调试下

**Comment by mcuking** [comment]
昨晚看懂了，是从app.jsx将路径传入到菜单组件，然后根据路径决定哪个菜单被选中，我在做的项目也这么改造了，很是感谢啊。。。
![image](https://user-images.githubusercontent.com/22924912/29345193-a88783b2-826f-11e7-99b7-50f069cf0705.png)

**Comment by yezihaohao** [comment]
😄不客气~我关issue了。有问题随时可以问哈
