### ISSUE TITLE
考虑一下把redux-alita改造为useContext?

### ISSUE THREAD

**Issue by fengertao** [yezihaohao/react-admin#91]
用redux-alita感觉代码很难理解。

自己练手把redux-alita改造成了useContext，感觉代码容易理解多了。
具体修改见
https://github.com/fengertao/react-admin/pull/2/files (这个PR是发给我自己repo的，不是发给本repo的)

UI新手，只有一个多月经验。代码难看，不要嘲笑。抛砖引玉。
有好多行修改是被VS代码自动格式化强迫修改的，请忽略。

**Comment by yezihaohao** [comment]
当然可以改造，用context，mobx，redux都可以，方案有很多，模板demo只提供一种解决方案，如果是练手或者熟悉代码可以自己重头写一遍，或者进行相应的改造。如果为了更快，更便捷的开发项目，用封装好的插件可能更好，当然你也可以自己重新封装个插件，为多个项目提供通用组件：）
