### ISSUE TITLE
异步表格请求数据报错

### ISSUE THREAD

**Issue by hellomolike** [yezihaohao/react-admin#93]
clone了博主的master分支的文件跑起来，异步访问表格数据没问题。换到router4.0分支包 就报错了
![图片](https://user-images.githubusercontent.com/36214418/69474079-e4cd5800-0df6-11ea-944f-e8620677b1c7.png)
![图片](https://user-images.githubusercontent.com/36214418/69474035-2dd0dc80-0df6-11ea-8f45-fc79c5e80765.png)

**Comment by yezihaohao** [comment]
老版本的接口停用了，参考最新版的代码
